name: Run ddtest

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  ddtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          api_key: ${{secrets.DD_API_KEY}}
          site: datadoghq.com

      - name: Run tests
        run: yarn test
        env:
          NODE_OPTIONS: -r ${{env.DD_TRACE_PACKAGE}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


