name: Run ddtest

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  ddtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Run tests
        run: yarn test
        env:
          NODE_OPTIONS: "-r $(pwd)/.pnp.cjs -r dd-trace/ci/init"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}


